name: Generate App Images (Windows, Linux, macOS)

on:
  pull_request:
    types: [closed]
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libx11-dev libxext-dev libxrender-dev

      - name: Install WiX Toolset (Windows only)
        if: runner.os == 'Windows'
        run: choco install wixtoolset

      - name: Make scripts executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x scripts/*.sh

      - name: Run Linux packaging script
        if: runner.os == 'Linux'
        run: bash scripts/build-tappas-linux.sh

      - name: Run Windows packaging script
        if: runner.os == 'Windows'
        run: scripts\\build-tappas-win.bat

      - name: Run macOS packaging script
        if: runner.os == 'macOS'
        run: bash scripts/build-tappas-macos.sh
        
      - name: Zip app folder (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir -p release
          zip -r release/tappAS-linux.zip dist/

      - name: Upload Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: tappAS-linux-zip
          path: release/tappAS-linux.zip
          
      - name: Zip app folder (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Force -Path release
          Compress-Archive -Path dist\* -DestinationPath release\tappAS-windows.zip

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: tappAS-windows-zip
          path: release/tappAS-windows.zip
          
      - name: Zip app folder (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p release
          zip -r release/tappAS-macos.zip dist/

      - name: Upload macOS artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: tappAS-macos-zip
          path: release/tappAS-macos.zip
          
          
  release:
    # if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout master after merge
        uses: actions/checkout@v4
        with:
          ref: master
          
      - name: Download ZIPs
        uses: actions/download-artifact@v4
        with:
          path: release-zips

      - name: Check ZIP integrity
        run: |
          ls -lh release-zips || { echo "release-zips folder not found"; exit 1; }
          test -f release-zips/tappAS-linux-zip/tappAS-linux.zip || { echo "tappAS-linux.zip not found"; exit 1; }
          test -f release-zips/tappAS-windows-zip/tappAS-windows.zip || { echo "tappAS-windows.zip not found"; exit 1; }
          test -f release-zips/tappAS-macos-zip/tappAS-macos.zip || { echo " tappAS-macos.zip not found"; exit 1; }

          echo " All ZIP files are generated correctly."
          
      - name: Read version
        id: version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT
        
      - name: Read release body from file
        id: body
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_BODY.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: tappAS ${{ steps.version.outputs.VERSION }}
          body: ${{ steps.body.outputs.BODY }}
          files: |
            release-zips/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          