name: Generate App Images (Windows, Linux, macOS)

on:
  pull_request:
    types: [closed]
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev libx11-dev libxext-dev libxrender-dev

      - name: Install WiX Toolset (Windows only)
        if: runner.os == 'Windows'
        run: choco install wixtoolset

      - name: Make scripts executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x scripts/*.sh

      - name: Run Linux packaging script
        if: runner.os == 'Linux'
        run: bash scripts/build-tappas-linux.sh

      - name: Run Windows packaging script
        if: runner.os == 'Windows'
        run: scripts\\build-tappas-win.bat

      - name: Run macOS packaging script
        if: runner.os == 'macOS'
        run: bash scripts/build-tappas-macos.sh

      - name: Upload Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: tappAS-linux
          path: dist/linux

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: tappAS-windows
          path: dist/win

      - name: Upload macOS artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: tappAS-macos
          path: dist/macos
          
          
  release:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: tappAS-linux
          path: dist/linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: tappAS-windows
          path: dist/win

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: tappAS-macos
          path: dist/macos

      - name: Checkout master tras el merge
        uses: actions/checkout@v4
        with:
          ref: master
          
      - name: Read version
        id: version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT
        
      - name: Read release body from file
        id: body
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          cat RELEASE_BODY.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: tappAS ${{ steps.version.outputs.VERSION }}
          body: ${{ steps.body.outputs.BODY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir binarios a la release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/linux/**
            dist/win/**
            dist/macos/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
